trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Build
  displayName: 'Build and Test'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      cd STEVE10MR/Upload_Container_Azure
      npm install
      npm run build
    displayName: 'npm install and build'

- job: Publish
  displayName: 'Publish Artifact'
  dependsOn: Build
  steps:
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/STEVE10MR/Upload_Container_Azure/dist'
      artifactName: 'drop'
    displayName: 'Publish Artifact'
