trigger:
- main

pool:
  vmImage: ubuntu-18.04

jobs:
- job: BuildAndPublish
  displayName: 'Build and Publish'
  steps:
    - task: UseNodeJs@1
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        cd STEVE10MR/Upload_Container_Azure
        npm install
        npm run build

      displayName: 'Build'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'dist'
        publishLocation: 'pipeline'
      displayName: 'Publish Artifact'

- job: DeployToAzure
  displayName: 'Deploy to Azure App Service'
  dependsOn: BuildAndPublish

  steps:
    - download: current
      artifact: 'dist'
      displayName: 'Download Artifact'

    - task: UseNodeJs@1
      inputs:
        versionSpec: '14.x'
        displayName: 'Install Node.js for deployment'

    - script: |
        npm install -g azure-functions-core-tools@3 --unsafe-perm=true
      displayName: 'Install Azure Functions Core Tools'

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: '<Nombre de tu servicio de conexión a Azure>'
        appType: 'webAppLinux'
        appName: 'uploadcontainer'  # Nombre de tu App Service en Azure
        packageForLinux: '$(Pipeline.Workspace)/dist'
        RuntimeStack: 'NODE|14.x'
      displayName: 'Deploy to Azure App Service'
