trigger:
- main

pool:
  vmImage: ubuntu-18.04

jobs:
- job: BuildAndPublish
  displayName: 'Build and Publish'
  steps:
    - task: UseNodeJs@1
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        cd STEVE10MR/Upload_Container_Azure
        npm install && npm run build

      displayName: 'Build and publish'