trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: BuildAndPublish
  displayName: 'Build and Publish'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'NPM Install and Build'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/dist'
      artifactName: 'drop'
    displayName: 'Publish Artifact'

- job: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: BuildAndPublish
  steps:
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Suscripción 1(b3630c1b-2ca7-4b9b-a1ad-f686c1a02f22)'
      appType: 'webApp'
      WebAppName: 'uploadcont'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    displayName: 'Deploy to Azure App Service'